kind = "mobile"
previewPath = "/hidayet/"
title = "Hidayet"
version = "1.0.0"
id = "artifacts/hidayet"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/hidayet/" ]
localPort = 25548

[services.development]
run = "pnpm --filter @workspace/hidayet run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hidayet", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/hidayet", "run", "serve" ]

[services.env]
PORT = "25548"
BASE_PATH = "/hidayet/"
